spring:
  application:
    name: "eurekaserver"
  config:
    import: "optional:configserver:http://localhost:8888/"
  cloud:
    compatibility-verifier:
      enabled: false
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

