spring:
  application:
    name: "favourite-service"
  config:
    import: optional:configserver:http://localhost:8888
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
