services:
  rabbit:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service
    networks:
      - abs

  configserver:
    image: "rood0/config-server-ms:s4"
    container_name: config-service-ms
    healthcheck:
      test: "curl --fail --silent localhost:8888/actuator/health/readiness | grep UP || exit 1"
      interval: 30s
      timeout: 10s
      retries: 20
      start_period: 20s
    ports:
      - "8888:8888"
    depends_on:
      rabbit:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-base-config
    networks:
      - abs

  eurekaserver:
    image: "rood0/service-registry-ms:s6"
    container_name: service-registry-ms
    ports:
      - "8761:8761"
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
    networks:
      - abs

  productsdb:
    container_name: productsdb
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: productsdb
    healthcheck:
      test: "mysqladmin ping -h localhost -u root --password=admin"
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - mysql-productsdb-data:/var/lib/mysql
    extends:
      file: common-config.yml
      service: microservice-db-config
    networks:
      - abs

  productservice:
    image: "rood0/product-service-ms:s9"
    container_name: product-service-ms
    ports:
      - "8083:8083"
    healthcheck:
      test: "curl --fail --silent localhost:8083/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      productsdb:
        condition: service_healthy
      authdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "product-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://productsdb:3306/productsdb"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "admin"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
    extends:
      file: common-config.yml
      service: microservice-eureka-config
    networks:
      - abs

  paymentdb:
    container_name: paymentdb
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: paymentdb
    healthcheck:
      test: "mysqladmin ping -h localhost -u root --password=admin"
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - mysql-paymentdb-data:/var/lib/mysql
    extends:
      file: common-config.yml
      service: microservice-db-config
    networks:
      - abs

  paymentservice:
    image: "rood0/payment-service-ms:s5"
    container_name: payment-service-ms
    ports:
      - "8400:8400"
    healthcheck:
      test: "curl --fail --silent localhost:8400/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      paymentdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "payment-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://paymentdb:3306/paymentdb"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "admin"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
    extends:
      file: common-config.yml
      service: microservice-eureka-config
    networks:
      - abs

  orderdb:
    container_name: orderdb
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: orderdb
    healthcheck:
      test: "mysqladmin ping -h localhost -u root --password=admin"
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - mysql-orderdb-data:/var/lib/mysql
    extends:
      file: common-config.yml
      service: microservice-db-config
    networks:
      - abs

  orderservice:
    image: "rood0/order-service-ms:s5"
    container_name: order-service-ms
    ports:
      - "8084:8084"
    healthcheck:
      test: "curl --fail --silent localhost:8084/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      orderdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "order-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://orderdb:3306/orderdb"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "admin"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
    extends:
      file: common-config.yml
      service: microservice-eureka-config
    networks:
      - abs

  cartdb:
    container_name: cartdb
    ports:
      - 3310:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: cartdb
    healthcheck:
      test: "mysqladmin ping -h localhost -u root --password=admin"
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - mysql-cartdb-data:/var/lib/mysql
    extends:
      file: common-config.yml
      service: microservice-db-config
    networks:
      - abs

  cartservice:
    image: "rood0/cart-service-ms:s7"
    container_name: cart-service-ms
    ports:
      - "8085:8085"
    healthcheck:
      test: "curl --fail --silent localhost:8085/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      cartdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cart-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cartdb:3306/cartdb"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "admin"
    extends:
      file: common-config.yml
      service: microservice-eureka-config
    networks:
      - abs

  authdb:
    container_name: authdb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: authdb
    healthcheck:
      test: "mysqladmin ping -h localhost -u root --password=admin"
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - mysql-authdb-data:/var/lib/mysql
    extends:
      file: common-config.yml
      service: microservice-db-config
    networks:
      - abs

  authservice:
    image: "rood0/auth-service-ms:s10"
    container_name: auth-service-ms
    ports:
      - "8081:8081"
    healthcheck:
      test: "curl --fail --silent localhost:8081/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      authdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "auth-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://authdb:3306/authdb"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "admin"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
    extends:
      file: common-config.yml
      service: microservice-eureka-config
    networks:
      - abs

  gatewayserver:
    image: "rood0/api-gateway-ms:s3"
    container_name: api-gateway-ms
    ports:
      - "9191:9191"
    depends_on:
      authservice:
        condition: service_healthy
      productservice:
        condition: service_healthy
      paymentservice:
        condition: service_healthy
      orderservice:
        condition: service_healthy
      cartservice:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
    extends:
      file: common-config.yml
      service: microservice-eureka-config
    networks:
      - abs

networks:
  abs:
    driver: "bridge"

volumes:
  mysql-productsdb-data:
    driver: local
  mysql-paymentdb-data:
    driver: local
  mysql-orderdb-data:
    driver: local
  mysql-cartdb-data:
    driver: local
  mysql-authdb-data:
    driver: local
