spring:
  application:
    name: "configserver"
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sefaksc/config-server.git
          timeout: 5
          clone-on-start: true
          force-pull: true
          default-label: main
server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true